### ISSUE TITLE
複数アプリでのロック不全

### ISSUE THREAD

**Issue by iwbchi** [so0352/AppBlockTaskList#52]
対象を複数アプリにした場合ロック処理が走らない
要調査

**Comment by so0352** [comment]
targetAppSelectRemake/so
にて応急処置のための、アプリを一つのみしか選択できない処理を追加

**Comment by iwbchi** [comment]
sql変更
LockSettingDao.kt 13L
    @Query("SELECT * FROM LockSetting WHERE targetApp LIKE  '%' || :packageName || '%'")
